##############################################################################
#
# Script: cluster.R
# Project: Dengue
# Author: David Glass
# Date: 9-8-20
#
# This program takes in a csv generated by fcs_to_csv.R and clusters
# data, then generates a csv of clustered data
#
# Instructions:
# Update USER INPUTS with directory locations
# Run script
#
# Versions:
# R 3.6.3
# Rstudio 1.3.1093
# MASS 7.3.54
# viridis 0.6.1
# uwot 0.1.10
# pheatmap 1.0.12
# FlowSOM 1.18.0
# tidyverse 1.3.1
# data.table 1.14.0
# 
##############################################################################



###### LIBRARIES ######

require(MASS)
require(viridis)
require(uwot)
require(pheatmap)
require(FlowSOM)
require(tidyverse)
require(data.table)



##### INPUTS #####

path <- "~/Research/phd/dengue/"
factors <- c("sample", "plate", "cluster", "type", "subtype", "population", "isotype")
denv <- c("DENV_NS1", "DENV_NS3", "DENV_ENV")
# process_dat.csv generated by fcs_to_csv
dat.path <- paste0(path, "tables/processed_dat.csv")
images.path <- paste0(path, "images/clustering/")



##### FUNCTIONS #####

somCluster <- function(dt, ch, ...) {
  # Clusters with a SOM
  # Inputs:
  #   dt - data.table with all of the data to be clustered
  #   ch - vector of channel names to cluster
  #   ... arguments passed onto FlowSOM::SOM function
  # Outputs:
  #   cluster assignment column
  set.seed(666)
  som.out <- SOM(as.matrix(dt[, ch, with=F]), ...)
  return(as.factor(som.out$mapping[,1]))
}


clusterData <- function(dt=dat) {
  # Calls somCluster and then metaclusters into ten populations
  # Inputs:
  #   dt - data.table
  # Outputs:
  #   dt - data.table with added meta.cluster column
  
  # Original UMAP:
  # subsampleWrapper(dt, 100000) %>%
  #   makeUMAP(dir.name="umap_initial")
  
  
  #####
  print("Ig Aggregate ID")
  #####
  # Eliminate Ig isotype aggregates
  channels <- c("CD38", "CD27", "IgM", "IgA", "IgG", "CD45RB")
  dt[, cluster:=somCluster(dt, ch=channels, xdim=15, ydim=15)]
  medians <- dt[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(dt[, cluster])))]
  
  # ggplot(medians, aes(CD19, CD38, fill=CD27, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.1) + geom_hline(yintercept=0.625)
  
  medians[CD19>0.1 & CD38>0.625, debris:=F]
  
  # ggplot(medians[is.na(debris)], aes(IgM, IgA, fill=CD45RB, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.4) + geom_hline(yintercept=0.5)
  
  medians[is.na(debris) & IgM>0.4 & IgA>0.5, debris:=T]
  
  # ggplot(medians[is.na(debris)], aes(CD45RB, IgM, fill=CD19, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.75) + geom_hline(yintercept=0.5)
  
  medians[is.na(debris) & CD45RB>0.75 & IgM<0.5, debris:=T]
  
  medians[is.na(debris), debris:=F]
  
  # ggplot(medians, aes(IgM, IgA, fill=debris, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() +
  #   theme(legend.position="none")
  # 
  # ggplot(medians, aes(IgA, IgG, fill=debris, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() +
  #   theme(legend.position="none")
  
  for (clust in medians$cluster) dt[cluster==clust, debris:=medians[cluster==clust, debris]]
  
  # ggplot(dt[debris==T], aes(IgA, IgM, color=IgG)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis()
  
  dt <- dt[debris==F]
  dt[, `:=`(cluster=NULL, debris=NULL)]
  rm(medians)
  
  
  #####
  print("CD24 Aggregate ID")
  #####
  # Eliminate CD24 isotype aggregates
  channels <- c("CD24", "CD16", "CD19", "DENV_NS1", "DENV_ENV")
  dt[, cluster:=somCluster(dt, ch=channels, xdim=15, ydim=15)]
  medians <- dt[, lapply(.SD, median), .SDcols=c(all.markers, denv), by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(dt[, cluster])))]
  
  medians[, debris:=F]
  
  # ggplot(medians, aes(CD19, CD16, fill=CD24, size=count)) + #geom_text(aes(label=cluster))
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B", limits=c(0,1)) +
  #   theme(legend.position="none") + geom_vline(xintercept=0.3) + geom_hline(yintercept=0.4)
  # 
  # ggplot(subsampleWrapper(dt, 100000), aes(CD19, CD16, color=CD24)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.3) +
  #   geom_hline(yintercept=0.4)
  
  medians[CD19>0.3 & CD16>0.4, debris:=T]
  
  # ggplot(medians[debris==F], aes(CD16, CD24, fill=CD19, size=count)) + #geom_text(aes(label=cluster))
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B", limits=c(0,1)) +
  #   theme(legend.position="none") + geom_vline(xintercept=0.2) + geom_hline(yintercept=0.45)
  
  medians[CD16>0.2 & CD24>0.5, debris:=T]
  
  for (clust in medians$cluster) dt[cluster==clust, debris:=medians[cluster==clust, debris]]
  
  # ggplot(dt[debris==T], aes(CD19, CD16, color=CD24)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis()
  
  dt <- dt[debris==F]
  dt[, `:=`(cluster=NULL, debris=NULL)]
  rm(medians)
  
  # ggplot(subsampleWrapper(dt, 100000), aes(CD45RB, CD24, color=CD16)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis()
  
  #####
  print("Split 1: Type")
  ### B, T, NK, Myeloid
  channels <- c("CD3", "CD4", "CD8a", "CD19", "CD38", "CD27", "CD45RA",
                "CD56", "CD16", "CD33", "CD14", "CD11c", "CD123")
  dt[, cluster:=somCluster(dt, ch=channels, xdim=12, ydim=12)]
  medians <- dt[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(dt[, cluster])))]
  
  medians[, debris:=F]
  
  # ggplot(medians, aes(CD3, CD19, fill=CD14, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.25) + geom_hline(yintercept=0.1)
  # 
  # ggplot(medians[debris==F], aes(CD3, CD33, fill=CD19, size=count)) + #geom_text(aes(label=cluster))
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.25) + geom_hline(yintercept=0.15)

  medians[CD3>0.25 & CD33>0.15, debris:=T]
  medians[CD3>0.25, type:="T"]
  
  # ggplot(medians[debris==F & is.na(type)], aes(CD19, CD38, fill=CD27, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.1)
  
  medians[is.na(type) & CD19>0.1, type:="B"]
  
  # ggplot(medians[debris==F & is.na(type)], aes(CD56, CD33, fill=CD45RA, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.45) + geom_hline(yintercept=0.7)
  # 
  # ggplot(subsampleWrapper(dt, 100000), aes(CD56, CD33, color=CD45RA)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis()
  # 
  # ggplot(medians[debris==F & is.na(type)], aes(CD11c, CD33, fill=CD45RA, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) +
  #   theme_bw() +
  #   scale_fill_viridis(option="B") +
  #   theme(legend.position="none") +
  #   geom_hline(yintercept=0.2)
  
  medians[is.na(type) & CD33>0.2, type:="M"]
  
  # ggplot(medians[debris==F & is.na(type)], aes(CD56, CD11c, fill=CD45RA, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") +
  #   geom_vline(xintercept=0.15)
  # 
  # ggplot(subsampleWrapper(dt[CD33<0.2 & CD19<0.2 & CD3<0.2], 100000), aes(CD56, CD11c, color=CD45RA)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.1)
  # 
  # ggplot(medians[debris==F & is.na(type)], aes(CD56, CD45RA, fill=CD123, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") +
  #   geom_vline(xintercept=0.15)

  
  medians[is.na(type) & CD56>0.15, type:="NK"]
  
  # ggplot(medians[debris==F & is.na(type)], aes(CD14, CD11c, fill=CD33, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.2) + geom_hline(yintercept=0.2)
  # 
  # ggplot(medians[debris==F & is.na(type)], aes(CD45RA, CD123, fill=CD11c, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.2) + geom_hline(yintercept=0.2)
  # 
  # ggplot(medians[debris==F & is.na(type) & CD14<0.2 & CD11c<0.2], aes(CD123, CD16, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() +# scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.1) + geom_hline(yintercept=0.1)

  medians[is.na(type) & CD14>0.2, type:="M"]
  medians[is.na(type) & CD11c>0.2, type:="M"]
  medians[is.na(type) & CD123>0.5, type:="M"]
  
  # ggplot(medians[debris==F & is.na(type)], aes(CD45RA, CD16, fill=CD56, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B", limits=c(0,1)) +
  #   theme(legend.position="none") + geom_vline(xintercept=0.2) + geom_hline(yintercept=0.2)
  
  medians[is.na(type) & CD45RA>0.5, type:="NK"]
  
  # ggplot(medians[debris==F & is.na(type)], aes(CD45, HLA_DR, fill=CD279, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) +
  #   theme_bw() +
  #   scale_fill_viridis(option="B", limits=c(0,1)) +
  #   theme(legend.position="none") +
  #   geom_vline(xintercept=0.2) +
  #   geom_hline(yintercept=0.2)
  
  medians[is.na(type), debris:=T]
  
  # dev.off()
  # makeHeatmap(medians[debris==F], markers=all.markers, factor.col="type", file.name="type_heatmap")
  
  
  for (clust in medians$cluster) dt[cluster==clust, `:=`(debris=medians[cluster==clust, debris],
                                                         type=medians[cluster==clust, type])]
  
  # subsampleWrapper(dt, 100000) %>%
  #   makeUMAP(dir.name="umap_debris_check", factor.col="debris", print.markers=channels)
  
  dt <- dt[debris==F]
  dt[, `:=`(cluster=NULL, debris=NULL)]
  rm(medians)
  
  # subsampleWrapper(dt, 100000) %>%
  #   makeUMAP(dir.name="umap_type", factor.col="type", print.markers=all.markers)
  # 
  # subsampleWrapper(dt, 100000, by.col="type") %>%
  #   makeViolins(factor.col="type", dir.name="violin_type")
  #####
  #####

  #####
  print("Split 2: NK")
  #####
  
  temp <- dt[type=="NK"]
  temp[, density:=getDensity(CD56, CD16, n=100)]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(CD56, CD16, color=density)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.1) +
  #   geom_hline(yintercept=0.1)
  # 
  # ggplot(subsampleWrapper(temp[CD56^2 + CD16^2 > 0.3^2], 100000), aes(CD56, CD16, color=density)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.1) +
  #   geom_hline(yintercept=0.1)
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(CD56, CD16, color=CD45RA)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis(limits=c(0,1))
  
  temp[CD56>0.1 & CD16>0.1, population:="NK_DP"]
  temp[CD56<0.1 & CD16>0.1, population:="NK_CD16"]
  temp[CD56>0.1 & CD16<0.1, population:="NK_CD56"]
  temp[CD56^2 + CD16^2 < 0.3^2, population:="NK_DN"]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(CD56, CD16, color=population)) +
  #   geom_point(size=0.25) + theme_bw()

  dt[type=="NK", `:=`(subtype="NK", population=temp$population)]
  
  # ggplot(subsampleWrapper(dt[type=="NK"], 100000), aes(CD56, CD16, color=population)) +
  #   geom_point(size=0.25) + theme_bw()
  # 
  # subsampleWrapper(dt[type=="NK"], 100000) %>%
  #   makeUMAP(dir.name="umap_NK", factor.col="population", umap.markers=all.markers, print.markers=all.markers)

  #####
  
  #####
  print("Split 3: Myeloid")
  ## subytpe: pDC, cDC, Mono, Basophil
  ## pDC, cDC1, cDC2, CD14+CD16-Mono, CD14+CD16+Mono, CD14-CD16+Mono, Basophil
  
  channels <- c("CD11c", "CD14", "CD16", "CD123", "CD1c", "CD33", "HLA_DR",
                "CD4", "CD32", "CD64", "CD45RA", "CD141", "CD45", "CD38")
  
  # subsampleWrapper(dt[type=="M"], 100000) %>%
  #   makeUMAP(dir.name="umap_M", umap.markers=channels, print.markers=channels)
  
  temp <- dt[type=="M"] %>%
    .[, cluster:=somCluster(., ch=channels, xdim=13, ydim=13)]
    
  medians <- temp[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(temp[, cluster])))]
  
  # ggplot(medians, aes(HLA_DR, CD123, fill=CD45RA, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.2) + geom_hline(yintercept=0.75)
  
  medians[CD123>0.75 & HLA_DR>0.2, `:=`(subtype="M_pDC", population="M_pDC")]
  medians[CD123>0.75 & HLA_DR<0.2, `:=`(subtype="M_Basophil", population="M_Basophil")]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(CD14, CD16, color=CD1c+CD141)) +
  #   geom_point(size=0.25) + theme_bw() + scale_color_viridis() +
  #   geom_vline(xintercept=0.125) +
  #   geom_hline(yintercept=0.2) +
  #   geom_hline(yintercept=0.4)
  # 
  # ggplot(medians[is.na(subtype) & CD14<0.25 & CD16<0.25], aes(CD14, CD16, fill=CD1c+CD141, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.03) + geom_hline(yintercept=0.1)
  # 
  # ggplot(medians[is.na(subtype)], aes(CD1c, CD141, fill=CD14+CD16, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.5) + geom_hline(yintercept=1)
  # 
  # ggplot(medians[is.na(subtype) & CD16<0.1 & CD14<0.03], aes(CD141, CD1c, fill=HLA_DR, size=count)) +
  #   #geom_text(aes(label=cluster))
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=1) + geom_hline(yintercept=0.5)
  
    
  medians[CD141>1, `:=`(subtype="M_cDC", population="M_cDC1")]
  medians[CD1c>0.5, `:=`(subtype="M_cDC", population="M_cDC2")]
  
  # ggplot(medians[is.na(subtype) & CD14<0.2 & CD16<0.2], aes(CD11c, CD33, fill=CD64, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B", limits=c(0,1)) +
  #   theme(legend.position="none") + geom_vline(xintercept=0.3) + geom_hline(yintercept=0.2)
  
  medians[is.na(subtype), subtype:="M_Monocyte"]
  
  # ggplot(medians, aes(CD14+CD16, CD141, fill=population, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw()

  # ggplot(medians[subtype=="M_Monocyte"], aes(CD14, CD16, fill=CD64, size=count)) +# geom_text(aes(label=cluster))
  #   geom_point(color="black", pch=21) +
  #   scale_fill_viridis() +
  #   scale_size_continuous(range = c(1, 5)) +
  #   theme_bw() +
  #   geom_vline(xintercept=0.28) +
  #   geom_hline(yintercept=0.2)
  # 
  # ggplot(subsampleWrapper(temp[CD14<0.2], 100000), aes(CD14, CD16, color=CD64)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.28) +
  #   geom_hline(yintercept=0.2)
  
  medians[subtype=="M_Monocyte" & CD16>0.2 & CD14<0.28, population:="M_Mono_CD16"]
  medians[subtype=="M_Monocyte" & CD16>0.2 & CD14>0.28, population:="M_Mono_DP"]
  medians[subtype=="M_Monocyte" & CD16<0.2 & CD14<0.28, population:="M_Mono_DN"]
  medians[subtype=="M_Monocyte" & CD16<0.2 & CD14>0.28, population:="M_Mono_CD14"]
  
  # makeHeatmap(medians, markers=channels, factor.col="population", file.name="M_heatmap")
  # dev.off()
  
  for (clust in medians$cluster) temp[cluster==clust, `:=`(subtype=medians[cluster==clust, subtype],
                                                           population=medians[cluster==clust, population])]
  
  # subsampleWrapper(temp, 100000) %>%
  #   makeUMAP(dir.name="umap_M", factor.col="population", umap.markers=channels, print.markers=NULL)
  # subsampleWrapper(temp, 100000) %>%
  #   makeUMAP(dir.name="umap_M", factor.col="subtype", umap.markers=channels, print.markers=NULL)
  
  dt[type=="M", `:=`(subtype=temp$subtype, population=temp$population)]
  
  #####
  #####
  
  
  #####
  print("Split 4: B")
  ### TransitionalB, NaiveB, MemoryB, AtypicalMemoryB, Plasma
  isotypes <- c("IgM", "IgD", "IgA", "IgG")
  channels <- c("CD27", "CD38", "CD19", "CD11c", "CD24", "CD45RA", "CD32", "CD23", isotypes)
  
  # subsampleWrapper(dt[type=="B"], 100000) %>%
  #   makeUMAP(dir.name="umap_B", umap.markers=channels, print.markers=channels)
  
  temp <- dt[type=="B"] %>%
    .[, cluster:=somCluster(., ch=channels, xdim=12, ydim=12)]
  
  medians <- temp[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(temp[, cluster])))]
  
  # ggplot(medians, aes(CD19, CD11c, fill=CD32, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.75) + geom_hline(yintercept=0.2)
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(CD19, CD11c, color=CD32)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.75) +
  #   geom_hline(yintercept=0.4)
  
  medians[CD19>0.75 & CD11c>0.2, population:="B_EffectorMemory"]
  
  # ggplot(medians[is.na(population)], aes(CD19, CD38, fill=CD27, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.55) + geom_hline(yintercept=0.55)
  
  medians[is.na(population) & CD19<0.55 & CD38>0.55, population:="B_Plasma"]
  
  # ggplot(medians[is.na(population)], aes(CD24, CD38, fill=IgM, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.45) + geom_hline(yintercept=0.45)
  
  medians[is.na(population) & CD38>0.45 & CD24>0.45, population:="B_Transitional"]
  
  # ggplot(medians[is.na(population)], aes(CD45RA, CD27, fill=CD24, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") +
  #   geom_hline(yintercept=0.3)
  
  temp[, density:=getDensity(CD45RA, CD27, n=50)]

  # ggplot(subsampleWrapper(temp, 100000), aes(CD45RA, CD27, color=density)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis() +
  #   geom_hline(yintercept=0.3)

  
  medians[is.na(population) & CD27>0.3, population:="B_cMemory"]
  
  # ggplot(medians[is.na(population)], aes(IgG, IgA, fill=IgD, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   geom_vline(xintercept=0.25) + geom_hline(yintercept=0.5)

  medians[is.na(population) & (IgG>0.25 | IgA>0.5), population:="B_cMemory"]
  medians[is.na(population), population:="B_Naive"]
  
  # makeHeatmap(medians, markers=channels, factor.col="population", file.name="B_heatmap")
  
  medians[population=="B_Plasma", subtype:="B_Plasma"]
  medians[population %in% c("B_Naive", "B_Transitional"), subtype:="B_Inexperienced"]
  medians[is.na(subtype), subtype:="B_Memory"]
  
  for (clust in medians$cluster) temp[cluster==clust, `:=`(subtype=medians[cluster==clust, subtype],
                                                           population=medians[cluster==clust, population])]
  
  # subsampleWrapper(temp, 100000) %>%
  #   makeUMAP(dir.name="umap_B", factor.col="population", umap.markers=channels, print.markers=NULL)
  # 
  # ggplot(subsampleWrapper(temp[population=="B_Naive"], 100000), aes(IgG, IgA, color=population)) +
  #   geom_point(size=0.25) +
  #   theme_bw()
  
  dt[type=="B", `:=`(subtype=temp$subtype, population=temp$population)]
  
  ### B cell isotype
  
  ## Trans/naive
  temp <- dt[subtype=="B_Inexperienced"]
  temp[, density:=getDensity(IgM, IgD, n=100)]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(IgM, IgD, color=density)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.12) +
  #   geom_hline(yintercept=0.15)
  
  temp[IgM>0.12 & IgD>0.15, isotype:="IgMD"]
  temp[is.na(isotype) & IgD>0.15, isotype:="IgD"]
  temp[is.na(isotype) & IgM>0.12, isotype:="IgM"]
  temp[is.na(isotype), isotype:="ND"]
  
  dt[subtype=="B_Inexperienced", `:=`(isotype=temp$isotype)]
  
  ### Memory
  
  temp <- dt[population %in% c("B_cMemory", "B_EffectorMemory")] %>%
    .[, cluster:=somCluster(., ch=c(isotypes), xdim=9, ydim=9)]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(IgG, IgA, color=IgM+IgD)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis()
  
  medians <- temp[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(temp[, cluster])))]
  
  # ggplot(medians, aes(IgG, IgA, fill=IgM+IgD, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.1)
  
  medians[IgG>0.1, isotype:="IgG"]
  
  # ggplot(medians[is.na(isotype)], aes(IgA, IgM, fill=IgD, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.3) + geom_hline(yintercept=0.4)
  
  medians[IgA>0.3 & IgM<0.4 & is.na(isotype), isotype:="IgA"]
  
  # ggplot(medians[is.na(isotype)], aes(IgM, IgD, fill=IgM+IgD, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.25) + geom_hline(yintercept=0.2)
  # 
  # ggplot(subsampleWrapper(temp[IgG<0.2 & IgA<0.2], 50000), aes(IgD, IgM, color=getDensity(IgD, IgM, n=50))) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.25) +
  #   geom_hline(yintercept=0.2)
  

  # ggplot(medians, aes(IgM, IgD, fill=isotype, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) +
  #   theme_bw() +
  #   geom_vline(xintercept=0.25) +
  #   geom_hline(yintercept=0.2)
  
  medians[is.na(isotype) & IgM>0.25 & IgD>0.2, isotype:="IgMD"]
  medians[is.na(isotype) & IgD>0.2, isotype:="IgD"]
  medians[is.na(isotype) & IgM>0.25, isotype:="IgM"]
  medians[is.na(isotype), isotype:="ND"]
  
  for (clust in medians$cluster) temp[cluster==clust, `:=`(isotype=medians[cluster==clust, isotype])]
  
  dt[population %in% c("B_cMemory", "B_EffectorMemory"), `:=`(isotype=temp$isotype)]
  
  
  ### Plasma
  
  temp <- dt[population=="B_Plasma"] %>%
    .[, cluster:=somCluster(., ch=c("IgG", "IgA", "IgM"), xdim=8, ydim=8)]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(IgA, IgG+IgM, color=cluster)) +
  #   geom_point(size=0.5) +
  #   #scale_color_viridis() +
  #   geom_abline(slope=2.5, intercept=-0.6) +
  #   geom_hline(yintercept=0.7)
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(IgM, IgG, color=IgA)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis()
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(IgM, IgA, color=IgG)) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis() +
  #   geom_hline(yintercept=0.4) +
  #   geom_vline(xintercept=0.3)
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(IgM+IgG, IgA+IgG, color=getDensity(IgM+IgG, IgA+IgG, n=50))) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis()
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(IgG, IgM+IgA, color=getDensity(IgG, IgM+IgA, n=50))) +
  #   geom_point(size=0.5) +
  #   scale_color_viridis()
  
  medians <- temp[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(temp[, cluster])))]
  
  # ggplot(medians, aes(IgG, IgA, fill=IgM, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.065)
  # 
  # ggplot(medians, aes(IgM, IgA, fill=IgG, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.065)

  medians[IgA>0.4, isotype:="IgA"]
  
  # ggplot(medians, aes(IgG, IgM, fill=isotype, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + #scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.08) + geom_hline(yintercept=0.4)
  # 
  # ggplot(medians[is.na(isotype)], aes(IgG, IgM, fill=IgD, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.08) + geom_hline(yintercept=0.4)
  
  medians[IgM>0.4, isotype:="IgM"]
  
  # ggplot(medians, aes(IgG, IgD, fill=isotype, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + #scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.08)
  # 
  # ggplot(medians, aes(IgG, IgM+IgA, fill=isotype, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + #scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.08) + geom_hline(yintercept=0.5)
  
  medians[IgM+IgA<0.5 & IgG>0.08, isotype:="IgG"]
  medians[is.na(isotype), isotype:="ND"]
  
  for (clust in medians$cluster) temp[cluster==clust, `:=`(isotype=medians[cluster==clust, isotype])]
  
  # ggplot(subsampleWrapper(temp, 100000), aes(IgM+IgG, IgA+IgG, color=isotype)) +
  #   geom_point(size=0.5)

  dt[population=="B_Plasma", `:=`(isotype=temp$isotype)]
  
  
  # subsampleWrapper(dt[type=="B"], 100000) %>%
  #   makeUMAP(dir.name="umap_B", factor.col="isotype", umap.markers=channels, print.markers=NULL)
  # 
  # ggplot(subsampleWrapper(dt[type=="B"], 100000), aes(IgG, IgA, color=isotype)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   facet_wrap(~population)
  # 
  # ggplot(subsampleWrapper(dt[type=="B"], 100000), aes(IgD, IgM, color=isotype)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   facet_wrap(~population)
  
  #####
  
  #####
  #####
  
  #####
  print("Split 5: T cells")
  channels <- c("CD4", "TCRgd", "CD8a", "CD56", "CD197", "CD45RA", "CD25", "FoxP3")
  
  # subsampleWrapper(dt[type=="T"], 100000) %>%
  #   makeUMAP(dir.name="umap_T", umap.markers=channels, print.markers=all.markers)
  
  temp <- dt[type=="T"] %>%
    .[, cluster:=somCluster(., ch=channels, xdim=12, ydim=12)]
  
  medians <- temp[, lapply(.SD, median), .SDcols=all.markers, by=cluster] %>%
    .[order(cluster)] %>%
    .[, count:=log2(as.vector(table(temp[, cluster])))]
  
  # makeHeatmap(medians, markers=channels, file.name="T_heatmap")
  # dev.off()
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(CD4, CD8a, color=TCRgd+CD56)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis()
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(TCRgd+CD56, CD8a, color=cluster==66)) +
  #   geom_point(size=0.25) +
  #   theme_bw()
  # 
  # ggplot(subsampleWrapper(temp[cluster %in% c(144, 66, 53, 65, 64, 52, 140)], 100000), aes(CD4, CD8a, color=cluster)) +
  #   geom_point(size=0.25) +
  #   theme_bw()
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(CD4, CD8a, color=cluster==65)) +
  #   geom_point(size=0.25) +
  #   theme_bw()
  # 
  # ggplot(medians, aes(CD4, CD8a, fill=TCRgd, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) +
  #   theme_bw() +
  #   scale_fill_viridis(option="B") +
  #   theme(legend.position="none") +
  #   geom_vline(xintercept=0.1) +
  #   geom_hline(yintercept=0.1) +
  #   geom_hline(yintercept=0.3)
  # 
  # ggplot(medians, aes(CD4, CD8a, label=cluster)) +
  #   geom_label() +
  #   theme_bw() +
  #   theme(legend.position="none") +
  #   geom_vline(xintercept=0.1) +
  #   geom_hline(yintercept=0.1) +
  #   geom_hline(yintercept=0.3)
  
  medians[, debris:=F]
  medians[CD4>0.1 & CD8a>0.3, debris:=T]
  medians[debris==F & CD8a>0.1, subtype:="T_CD8"]
  medians[debris==F & CD4>0.1, subtype:="T_CD4"]
  medians[debris==F & CD8a<0.1 & CD4<0.1, subtype:="T_DN"]

  # ggplot(medians[debris==F & subtype=="T_DN"], aes(CD56, TCRgd, fill=CD16, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() + scale_fill_viridis(option="B") +
  #   theme(legend.position="none") + geom_vline(xintercept=0.15) + geom_hline(yintercept=0.2)

  medians[CD56>0.15, population:="T_NKT"]
  medians[TCRgd>0.2, population:="T_GD"]
  medians[subtype=="T_DN" & is.na(population), population:="T_DN_other"]
  
  # ggplot(medians, aes(CD25, FoxP3, fill=subtype, size=count)) + geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 15)) + theme_bw() + geom_vline(xintercept=0.5) +geom_hline(yintercept=0.6)
  # 
  # ggplot(subsampleWrapper(temp[CD4>0.3], 100000), aes(CD25, FoxP3, color=CD8a)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.5) +
  #   geom_hline(yintercept=0.6)
  
  medians[subtype=="T_CD4" & FoxP3>0.6 & CD25>0.5, population:="T_Treg"]
  
  # ggplot(medians[is.na(population) & debris==F], aes(CD45RA, CD197, fill=subtype, size=count)) +
  #   geom_point(color="black", pch=21) +
  #   scale_size_continuous(range = c(1, 5)) + theme_bw() +
  #   geom_vline(xintercept=0.15) + geom_hline(yintercept=0.15)
  # 
  # ggplot(subsampleWrapper(temp, 100000), aes(CD45RA, CD197, color=CD4)) +
  #   geom_point(size=0.25) +
  #   theme_bw() +
  #   scale_color_viridis() +
  #   geom_vline(xintercept=0.15) +
  #   geom_hline(yintercept=0.15)
  
  medians[is.na(population) & CD45RA<0.15 & CD197<0.15, population:=paste0(subtype, "_EM")]
  medians[is.na(population) & CD45RA>0.15 & CD197<0.15, population:=paste0(subtype, "_EMRA")]
  medians[is.na(population) & CD45RA>0.15 & CD197>0.15, population:=paste0(subtype, "_Naive")]
  medians[is.na(population) & CD45RA<0.15 & CD197>0.15, population:=paste0(subtype, "_CM")]
  
  # makeHeatmap(medians[debris==F], markers=channels, factor.col="population", file.name="T_heatmap")
  
  for (clust in medians$cluster) temp[cluster==clust, `:=`(subtype=medians[cluster==clust, subtype],
                                                           population=medians[cluster==clust, population],
                                                           debris=medians[cluster==clust, debris])]
  
  # subsampleWrapper(temp[debris==F], 100000) %>%
  #   makeUMAP(dir.name="umap_T", factor.col="population", umap.markers=channels, print.markers=all.markers)
  
  dt[type=="T", `:=`(subtype=temp$subtype, population=temp$population, debris=temp$debris)]
  dt <- dt[is.na(debris) | debris==F]
  dt[, debris:=NULL]
  rm(medians)
  
  #####
  
  # subsampleWrapper(dt, 200000) %>%
  #   makeUMAP(dir.name="umap_end", factor.col="subtype", print.markers=all.markers)
  # subsampleWrapper(dt, 200000) %>%
  #   makeUMAP(dir.name="umap_end", factor.col="population", print.markers=denv)
  # 
  # medians <- dt[, lapply(.SD, median), .SDcols=all.markers, by=subtype]
  # med.matrix <- as.matrix(medians[, c(all.markers, "subtype"), with=F], rownames="subtype") %>% t()
  # pheatmap(mat=med.matrix, color=inferno(n=20), border_color="black", clustering_method="ward.D2",
  #          filename=paste0(images.path, "subtype_heatmap.png"), width=18, height=9)
  # 
  # medians <- dt[, lapply(.SD, median), .SDcols=all.markers, by=population]
  # med.matrix <- as.matrix(medians[, c(all.markers, "population"), with=F], rownames="population") %>% t()
  # pheatmap(mat=med.matrix, color=inferno(n=20), border_color="black", clustering_method="ward.D2",
  #          filename=paste0(images.path, "population_heatmap.png"), width=18, height=9)
  
  return(dt)
}


subsampleWrapper <- function(tab, n.sample, by.col=NULL) {
  # Wrapper function for subsampling
  # Inputs:
  #   tab - a data.table
  #   n.sample - number of observations to sample
  #   by.col - if equally subsampling by column, the column to subsample by; if NULL, random subsample
  # Outputs:
  #   subsampled data.table
  set.seed(666)
  if(is.null(by.col)) return(tab[, .SD[sample(.N, n.sample)]])
  return(tab[, .SD[sample(.N, n.sample)], by=eval(by.col)])
}


makeHeatmap <- function(med, markers=all.markers, factor.col=NULL, ip=images.path, file.name) {
  # Makes a heatmap of the median expression values
  # Inputs:
  #   med - data.table of marker medians
  #   markers - character vector of markers to visualize
  #   factor.col - If side-coloring by factor, the factor column to color by, default NULL
  #   ip - vector of path
  #   file.name - name of file
  # Outputs:
  #   eps of of heatmap
  ac <- NA
  if(!is.null(factor.col)) {
    ac <- med[, factor.col, with=F] %>%
      as.data.frame()
    rownames(ac) <- med$cluster
  } 
  med.matrix <- as.matrix(med[, c(markers, "cluster"), with=F], rownames="cluster") %>% t()
  pheatmap(mat=med.matrix, color=inferno(n=20), border_color="black", clustering_method="ward.D2",
           filename=paste0(ip, file.name, ".png"), width=18, height=9, annotation_col=ac)
}


makeViolins <- function(subsampled, markers=all.markers, factor.col, ip=images.path, dir.name) {
  # Makes vioin plots by factor.col for markers
  # Inputs:
  #   subsampled - a (subsampled) data.table
  #   markers - character vector of markers to visualize
  #   factor.col - which column to separate cells by
  #   ip - path to images directory
  #   dir.name - name of directory
  # Outputs:
  #   Creates a directory within ip called dir.name and populates it with png files
  pa <- paste0(ip, dir.name, "/")
  if (!dir.exists(pa)) dir.create(pa)
  
  for (marker in markers) {
    print(marker)
    subsampled[, median.value:=median(eval(parse(text=marker))), by=eval(parse(text=factor.col))]
    ggplot(subsampled, aes(eval(parse(text=factor.col)), eval(parse(text=marker)), fill=median.value)) +
      geom_violin(scale="width") +
      theme_bw() + labs(x=NULL, y=NULL, title=marker) +
      scale_fill_viridis(option="B", limits=c(0,1)) +
      theme(legend.position="none", axis.text.x=element_text(angle=45, hjust=1))
    ggsave(paste0(pa, marker, ".png"), width=8, height=4)
  }
}


makeUMAP <- function(subsampled, ip=images.path, dir.name, umap.markers=all.markers, factor.col=NULL,
                     print.markers=all.markers, point.size=1, n.neighbors=15L, min.dist=0.3) {
  # Generates umap
  # Inputs:
  #   subsampled - a (subsampled) data.table
  #   ip - path to images folder
  #   dir.name - directory name
  #   umap.markers - channel names used to make the manifold
  #   factor.col - If coloring by factor, the factor column to color by, default NULL
  #   print.markers - channel names to color overlay umap
  #   point.size - size of points in geom_point
  #   n.neighbors - n_neighbors (uwot::umap) integer
  #   min.dist - min_dist (uwot::umap) scalar
  # Outputs:
  #   png of umaps
  pa <- paste0(ip, dir.name, "/")
  if (!dir.exists(pa)) dir.create(pa)
  
  set.seed(666)
  umap.out <- umap(subsampled[, umap.markers, with=F], n_neighbors=n.neighbors, min_dist=min.dist)
  subsampled[, `:=`(umap.1=umap.out[,1], umap.2=umap.out[,2])]
  
  # factor.col
  if (!is.null(factor.col)) {
    ggplot(subsampled, aes(umap.1, umap.2, color=eval(parse(text=factor.col)))) +
      geom_point(size=point.size) +
      theme_bw() + labs(x=NULL, y=NULL, color=factor.col) +
      theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
            axis.ticks=element_blank(), axis.text=element_blank()) +
      guides(colour=guide_legend(override.aes=list(size=3))) # this increases legend point size
    ggsave(paste0(pa, "z_", factor.col, ".png"), width=9, height=8)
  }
  
  # markers
  for (marker in print.markers) {
    print(marker)
    subsampled[eval(parse(text=marker))>1, eval(quote(marker)):=1]
    ggplot(subsampled, aes(umap.1, umap.2, color=eval(parse(text=marker)))) +
      geom_point(size=point.size) +
      theme_bw() + labs(x=NULL, y=NULL, title=marker) +
      scale_color_viridis(option="B", limits=c(0,1)) +
      theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(),
            axis.ticks=element_blank(), axis.text=element_blank(), legend.position="none")
    ggsave(paste0(pa, marker, ".png"), width=9, height=8)
  }
}


getDensity <- function(x, y, ...) {
  # Returns the 2D density vector for two numeric vectors
  # Inputs:
  #   x, y - numeric vectors
  #   ... additional arguments passed onto kde2d
  # Outputs:
  #   vector of density values
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}



##### MAIN ######

dat <- fread(dat.path, stringsAsFactors=T)
all.markers <- setdiff(colnames(dat), c(factors, denv))
dat <- clusterData()

dat <- dat[, setdiff(colnames(dat), c("CD45RB", "barium", "DNA_3")), with=F]
setnames(dat, c("CD152", "CD197", "CD8a", "CD274", "CD279"),
         c("CTLA_4", "CCR7", "CD8", "PD_L1", "PD_1"))

fwrite(dat, paste0(path, "tables/clustered_dat.csv"))

samples <- fread(paste0(path, "tables/clustered_dat.csv")) %>%
  .[, .(sample, plate)] %>%
  unique() %>%
  .[order(sample)]

fwrite(samples, paste0(path, "tables/metadata_stripped.csv"))

