##############################################################################
#
# Script: integrate_and_subsample.R
# Project: Dengue
# Author: David Glass
# Date: 10-29-20
#
# This program takes in a csv generated by cluster.R and a csv of metadata,
# integrates them, and outputs various subsamplings.
#
# Instructions:
# Update USER INPUTS with directory locations
# Run script
#
# Versions:
# R 3.6.3
# Rstudio 1.3.1093
# MASS 7.3.54
# tidyverse 1.3.1
# data.table 1.14.0
# 
##############################################################################



##### LIBRARIES #####

require(MASS)
require(tidyverse)
require(data.table)



##### INPUTS #####

path <- "~/Research/phd/dengue/tables/"
# metadata.csv placed by user
metadata.path <- paste0(path, "metadata.csv")
# generated by cluster.R
dat.path <- paste0(path, "clustered_dat.csv")



##### FUNCTIONS #####

subsample <- function(dt=dat, max.number) {
  # Subsample dt to max.number of cells per sample
  # Inputs:
  #   dt - a data.table
  #   max.number - max number of cells per sample
  # Outputs:
  #   dt - a data.table
  counts <- dt[, .N, by=sample_name] %>%
    .[, sam:=N>max.number]
  to.sample <- counts$sample_name[which(counts$sam)]
  set.seed(666)
  dt[sample_name %in% to.sample, .SD[sample(.N, max.number)], by=sample_name] %>%
    rbind(dt[!sample_name %in% to.sample]) %>%
    return()
}



getDensity <- function(x, y, ...) {
  # Returns the 2D density vector for two numeric vectors
  # Inputs:
  #   x, y - numeric vectors
  #   ... additional arguments passed onto kde2d (probably n, number of grid point in each direction)
  # Outputs:
  #   vector of density values
  dens <- kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}



##### MAIN #####

dat <- fread(dat.path) %>%
  .[, plate:=NULL] %>%
  merge(fread(metadata.path), all.x=T, by="sample") %>%
  setnames("sample", "sample_name")

fwrite(dat, paste0(path, "full_dat.csv"))
fwrite(subsample(max.number=20000), paste0(path, "20k_dat.csv"))
fwrite(subsample(max.number=10000), paste0(path, "10k_dat.csv"))
fwrite(subsample(max.number=5000), paste0(path, "5k_dat.csv"))